services:
    server:
      build: ./server
      ports:
        - 5050:5000
      command: npm run dev
      volumes:
        - ./server/src/:/app/src
    mongodb:
      image: mongo
      volumes:
        - ./data:/data/db
    client:
      build: ./client
      ports:
        - 5566:5173
      command: npm run dev
      volumes:
        - ./client/src/:/app/src